apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ingress-petstoreservices
  name: nginx-ingress-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "update", "delete"]

