apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress-rolebinding
  namespace: ingress-petstoreservices
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-petstoreservices
roleRef:
  kind: Role
  name: nginx-ingress-role
  apiGroup: rbac.authorization.k8s.io

